import sys

def printUsage():

    print ("""
    NAME
        rename_crowd_env_pdb.py

    DESCRIPTION

        Python script for renaming the chains in the initial position file generated by trajectory2dcd. In the pdb generated by trajectory2dcd the chains name are taken from the pdb filein the Solute Grid which may results in all the solutes having all chains named A. The scripts rename the first solute's chain A, for the second chain B and from third solute on (crowders) chain C. 

    ARGUMENTS

        It takes 2 parameters:
        1.)     Name of pdb file with che chains you want to rename
        2.)     Name of the output file
        

    EXAMPLE

        python rename_crowd_env_pdb.py reference.pdb reference_renamed.pdb


    """)

#file_in="/hits/basement/mcm/beccarro/Crowded_Env/haspin-CTU-Abraham/assoc_csurf_150_helix1Traj/reference.pdb"
#file_out="/hits/basement/mcm/beccarro/Crowded_Env/haspin-CTU-Abraham/assoc_csurf_150_helix1Traj/reference_diff_chains.pdb"

if "-h" in sys.argv:
    print(printUsage())
    sys.exit()

file_in=sys.argv[1]
file_out=sys.argv[2]

found_prot=False
found_lig=False
chain="A"
with open(file_out,"w+") as fout:
    with open(file_in,"r") as fin:
        for line_idx,line in enumerate(fin):
            if line.split()[0]=="TER" or line_idx==0:
                if found_prot==False:
                    found_prot=True
                else:
                    if found_lig==False:
                        found_lig=True
                        chain="B"
                        #chang chain for lig ->B
                    else:
                        #chain chain for crows -> C
                        chain="C"
                fout.write(line)
            else:
                fout.write(line[:21]+chain+line[22:])


