import re
import argparse
import os
import shutil

def main(args):

    # Define the file path
    file_path = os.path.join(os.getcwd()+"/Hydropro_calculation/" ,args.output_file)

    #Create folder if it does not exists
    if os.path.exists(args.folder_name)==False:
        os.mkdir(args.folder_name)

    # Read the file and extract the value
    with open(file_path, "r") as file:
        for line in file:
            match = re.search(r"The value of Translational diffusion coefficient .*:\s+([\d.E+-]+)", line)
            if match:
                translational_diffusion = float(match.group(1))
                print(f"Translational diffusion coefficient (Ang²/ps): {translational_diffusion}")
                with open(args.file_name, 'a+') as fout:
                    fout.write(str(translational_diffusion))
                break  # Stop after finding the first match

if __name__ == "__main__":
    
    parser = argparse.ArgumentParser(description="extracting translational diffusion coefficient from Hydropro output file")
    parser.add_argument('--output_file', type=str, help="name of the output file generated by Hydropro",required=True)
    parser.add_argument('--folder_name', type=str, help="name of the folder where to save the translational diffusion coefficient",required=True)
    parser.add_argument('--file_name', type=str, help="name of the file where to save the translational diffusion coefficient",required=True)
    
    args=parser.parse_args()
    
    main(args)

